/******************************************************************************
 * Project           : PLUS33 Coffee ERP
 * Developed By      : Haulo
 * Developed For     : PLUS33 Coffee
 * Developer         : Sivasurya
 *
 * Module            : Bi Module
 * Package           : com.plus33.erp.bi.entity
 * File              : BiWarehouseVersion.java
 * Purpose           : JPA Entity representing a persistent database record in Bi Module
 * Version           : 0.0.1-SNAPSHOT
 *
 * Related Controller: BiWarehouseVersionController
 * Related Service   : BiWarehouseVersionService, BiWarehouseVersionServiceImpl
 * Related Repository: BiWarehouseVersionRepository
 * Related Entity    : BiWarehouseVersion
 * Related DTO       : N/A
 * Related Mapper    : BiWarehouseVersionMapper
 * Related DB Table  : bi_warehouse_version
 * Related REST APIs : N/A
 * Depends On        : None
 * Used By           : BiWarehouseVersionRepository, BiWarehouseVersionMapper
 *
 * Description
 * ---------------------------------------------------------------------------
 * JPA Entity mapped to 'bi_warehouse_version'. Defines persistent domain object for Bi Module with validation, relationship mappings, and lifecycle callbacks.
 ******************************************************************************/
package com.plus33.erp.bi.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * <b>PLUS33 Coffee ERP -- Bi Module</b>
 *
 * <p><b>Class  :</b> {@code BiWarehouseVersion}</p>
 * <p><b>Package:</b> {@code com.plus33.erp.bi.entity}</p>
 * <p><b>Layer  :</b> JPA Entity: persistent domain object mapped to PostgreSQL table 'bi_warehouse_version'.</p>
 *
 * <p><b>Database Table   :</b> {@code bi_warehouse_version}</p>
 * <p><b>Module Deps      :</b> None</p>
 *
 * @author Sivasurya (Developed for PLUS33 Coffee by Haulo)
 * @version 0.0.1-SNAPSHOT
 */
@Entity
@Table(name = "bi_warehouse_version")
public class BiWarehouseVersion {
    /**
     * Retrieves id data from the database.
     *
     * @param id the unique database ID of the resource
     * @return the numeric result value
     * @throws ResourceNotFoundException if the entity is not found
     */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;
    @Column(name = "warehouse_version", nullable = false, unique = true, length = 50) private String warehouseVersion;
    @Column(name = "migration_version", nullable = false, length = 50) private String migrationVersion;
    @Column(name = "schema_checksum", length = 200) private String schemaChecksum;
    @Column(name = "generated_at", nullable = false, updatable = false) private LocalDateTime generatedAt = LocalDateTime.now();
    @Column(name = "generated_by", nullable = false, length = 100) private String generatedBy = "system";
    public Long getId() { return id; } public void setId(Long id) { this.id = id; }
    /**
     * Retrieves warehouse version data from the database.
     *
     * @param v the v input value
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getWarehouseVersion() { return warehouseVersion; } public void setWarehouseVersion(String v) { this.warehouseVersion = v; }
    /**
     * Retrieves migration version data from the database.
     *
     * @param v the v input value
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getMigrationVersion() { return migrationVersion; } public void setMigrationVersion(String v) { this.migrationVersion = v; }
    /**
     * Retrieves schema checksum data from the database.
     *
     * @param v the v input value
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getSchemaChecksum() { return schemaChecksum; } public void setSchemaChecksum(String v) { this.schemaChecksum = v; }
    /**
     * Retrieves generated at data from the database.
     *
     * @return the LocalDateTime result
     * @throws ResourceNotFoundException if the entity is not found
     */
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    /**
     * Retrieves generated by data from the database.
     *
     * @param v the v input value
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getGeneratedBy() { return generatedBy; } public void setGeneratedBy(String v) { this.generatedBy = v; }
}