/******************************************************************************
 * Project           : PLUS33 Coffee ERP
 * Developed By      : Haulo
 * Developed For     : PLUS33 Coffee
 * Developer         : Sivasurya
 *
 * Module            : Platform Module
 * Package           : com.plus33.erp.platform.entity
 * File              : PlatformEsgAuditLog.java
 * Purpose           : JPA Entity representing a persistent database record in Platform Module
 * Version           : 0.0.1-SNAPSHOT
 *
 * Related Controller: PlatformEsgAuditLogController
 * Related Service   : PlatformEsgAuditLogService, PlatformEsgAuditLogServiceImpl
 * Related Repository: PlatformEsgAuditLogRepository
 * Related Entity    : PlatformEsgAuditLog
 * Related DTO       : N/A
 * Related Mapper    : PlatformEsgAuditLogMapper
 * Related DB Table  : platform_esg_audit_log
 * Related REST APIs : N/A
 * Depends On        : None
 * Used By           : PlatformEsgAuditLogRepository, PlatformEsgAuditLogMapper
 *
 * Description
 * ---------------------------------------------------------------------------
 * JPA Entity mapped to 'platform_esg_audit_log'. Defines persistent domain object for Platform Module with validation, relationship mappings, and lifecycle callbacks.
 ******************************************************************************/
package com.plus33.erp.platform.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * <b>PLUS33 Coffee ERP -- Platform Module</b>
 *
 * <p><b>Class  :</b> {@code PlatformEsgAuditLog}</p>
 * <p><b>Package:</b> {@code com.plus33.erp.platform.entity}</p>
 * <p><b>Layer  :</b> JPA Entity: persistent domain object mapped to PostgreSQL table 'platform_esg_audit_log'.</p>
 *
 * <p><b>Database Table   :</b> {@code platform_esg_audit_log}</p>
 * <p><b>Module Deps      :</b> None</p>
 *
 * @author Sivasurya (Developed for PLUS33 Coffee by Haulo)
 * @version 0.0.1-SNAPSHOT
 */
@Entity
@Table(name = "platform_esg_audit_log")
public class PlatformEsgAuditLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "report_version", nullable = false)
    @NotNull
    @Size(max = 50)
    private String reportVersion;

    @Column(name = "report_hash", nullable = false)
    @NotNull
    @Size(max = 256)
    private String reportHash;

    @Column(name = "generated_by", nullable = false)
    @NotNull
    @Size(max = 100)
    private String generatedBy;

    @Column(name = "approved_by", nullable = false)
    @NotNull
    @Size(max = 100)
    private String approvedBy;

    @Column(name = "approval_date", nullable = false)
    @NotNull
    private LocalDateTime approvalDate;

    @Column(name = "digital_signature", nullable = false, columnDefinition = "TEXT")
    @NotNull
    private String digitalSignature;

    @Column(name = "trace_id", nullable = false)
    @NotNull
    @Size(max = 100)
    private String traceId;

    @Column(name = "audited_at", nullable = false)
    @NotNull
    private LocalDateTime auditedAt = LocalDateTime.now();

    /**
     * Retrieves id data from the database.
     *
     * @return the numeric result value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public Long getId() { return id; }
    /**
     * Performs the setId operation in this module.
     *
     * @param id the unique database ID of the resource
     */
    public void setId(Long id) { this.id = id; }
    /**
     * Retrieves report version data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getReportVersion() { return reportVersion; }
    /**
     * Performs the setReportVersion operation in this module.
     *
     * @param reportVersion the reportVersion input value
     */
    public void setReportVersion(String reportVersion) { this.reportVersion = reportVersion; }
    /**
     * Retrieves report hash data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getReportHash() { return reportHash; }
    /**
     * Performs the setReportHash operation in this module.
     *
     * @param reportHash the reportHash input value
     */
    public void setReportHash(String reportHash) { this.reportHash = reportHash; }
    /**
     * Retrieves generated by data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getGeneratedBy() { return generatedBy; }
    /**
     * Performs the setGeneratedBy operation in this module.
     *
     * @param generatedBy the generatedBy input value
     */
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }
    /**
     * Retrieves approved by data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getApprovedBy() { return approvedBy; }
    /**
     * Performs the setApprovedBy operation in this module.
     *
     * @param approvedBy the approvedBy input value
     */
    public void setApprovedBy(String approvedBy) { this.approvedBy = approvedBy; }
    /**
     * Retrieves approval date data from the database.
     *
     * @return the LocalDateTime result
     * @throws ResourceNotFoundException if the entity is not found
     */
    public LocalDateTime getApprovalDate() { return approvalDate; }
    /**
     * Performs the setApprovalDate operation in this module.
     *
     * @param approvalDate the approvalDate input value
     */
    public void setApprovalDate(LocalDateTime approvalDate) { this.approvalDate = approvalDate; }
    /**
     * Retrieves digital signature data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getDigitalSignature() { return digitalSignature; }
    /**
     * Performs the setDigitalSignature operation in this module.
     *
     * @param digitalSignature the digitalSignature input value
     */
    public void setDigitalSignature(String digitalSignature) { this.digitalSignature = digitalSignature; }
    /**
     * Retrieves trace id data from the database.
     *
     * @return the result string value
     * @throws ResourceNotFoundException if the entity is not found
     */
    public String getTraceId() { return traceId; }
    /**
     * Performs the setTraceId operation in this module.
     *
     * @param traceId the traceId input value
     */
    public void setTraceId(String traceId) { this.traceId = traceId; }
    /**
     * Retrieves audited at data from the database.
     *
     * @return the LocalDateTime result
     * @throws ResourceNotFoundException if the entity is not found
     */
    public LocalDateTime getAuditedAt() { return auditedAt; }
    /**
     * Performs the setAuditedAt operation in this module.
     *
     * @param auditedAt the auditedAt input value
     */
    public void setAuditedAt(LocalDateTime auditedAt) { this.auditedAt = auditedAt; }
}