/******************************************************************************
 * Project           : PLUS33 Coffee ERP
 * Developed By      : Haulo
 * Developed For     : PLUS33 Coffee
 * Developer         : Sivasurya
 *
 * Module            : Auth Module
 * File              : TokenResponse.java
 * Path              : src/main/java/com/plus33/erp/auth/dto/TokenResponse.java
 * Purpose           : Carries the signed JWT access token, token type, and expiry
 *                     duration returned by the login endpoint on successful authentication.
 * Version           : 1.0.0
 *
 * Description
 * ---------------------------------------------------------------------------
 * Immutable Java record representing the HTTP response body returned by
 * AuthController.login() after successful credential verification.
 * Contains three fields:
 *
 *   accessToken — signed JWT string generated by JwtService using the
 *                 configured secret key. Clients must include this token
 *                 in subsequent requests as Authorization: Bearer {accessToken}.
 *   tokenType   — always "Bearer" per OAuth2 / JWT convention, used by
 *                 the frontend apiClient to construct authorization headers.
 *   expiresIn   — token validity duration in seconds resolved from
 *                 JwtService.getExpirationSeconds(). Frontend uses this
 *                 to schedule session expiry warnings.
 *
 * Serialized to JSON by Spring MVC Jackson and returned inside ApiResponse
 * wrapper. Does not persist to any database table.
 ******************************************************************************/
package com.plus33.erp.auth.dto;

public record TokenResponse(

        String accessToken,
        String tokenType,
        long expiresIn
) {}
