spring.application.name=plus33-erp
spring.datasource.url=jdbc:postgresql://localhost:5432/plus33_erp
spring.datasource.username=postgres
spring.datasource.password=crazy@8
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.clean-on-validation-error=true
spring.flyway.clean-disabled=false
spring.flyway.validate-on-migrate=false

spring.devtools.restart.enabled=false

app.jwt.secret=plus33-erp-jwt-secret-key-must-be-at-least-256-bits-long-for-hmac-sha256
app.jwt.expiration-minutes=60

jwt.secret=plus33-super-secret-key-for-development-minimum-32-characters
jwt.issuer=plus33-erp
jwt.expiration-seconds=3600

server.address=127.0.0.1

server.max-http-request-header-size=10485760
