-- ============================================================================
-- Project           : PLUS33 Coffee ERP
-- Developed By      : Haulo
-- Developed For     : PLUS33 Coffee
-- Developer         : Sivasurya
--
-- Migration Version : 100
-- File              : V100__seed_wms_tier1_master_data.sql
-- Operation Type    : Seed Data / Permission Grant
-- Purpose           : seed wms tier1 master data
--
-- Tables Created    : N/A
-- Tables Altered    : N/A
-- Seed Data For     : N/A
-- Indexes           : N/A
--
-- Notes
-- ----------------------------------------------------------------------------
-- Flyway migration applied automatically on application startup.
-- Do NOT modify after applying to any environment.
-- ============================================================================
-- V100: Seed Tier-1 WMS Master Data
-- No-op seed script for Flyway baseline compatibility
SELECT 1;
