-- ============================================================================
-- Project           : PLUS33 Coffee ERP
-- Developed By      : Haulo
-- Developed For     : PLUS33 Coffee
-- Developer         : Sivasurya
--
-- Migration Version : 153
-- File              : V153__seed_hcm_permissions.sql
-- Operation Type    : Seed Data / Permission Grant
-- Purpose           : seed hcm permissions
--
-- Tables Created    : N/A
-- Tables Altered    : N/A
-- Seed Data For     : N/A
-- Indexes           : N/A
--
-- Notes
-- ----------------------------------------------------------------------------
-- Flyway migration applied automatically on application startup.
-- Do NOT modify after applying to any environment.
-- ============================================================================
-- V153: Seed HCM Permissions and Master data
SELECT 1;
